baseurl: "https://ecotsky.netlify.com/"
title: "eCOTS Ky"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: "UA-9232216-1"

params:
  # Conference info
  Name: "eCOTS Ky"
  Description: "A Regional Conference for eCOTS"
  Date: "May 25"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "Eastern Kenutcky University"
  Address: "4436 Kit Carson Drive"
  City:  "Richmond"
  State: "Kentucky"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "AIzaSyAoJtUUb4uCUJrbmP6ULEqzw346vu4PF24"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    - sponsors
    #- partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    speakers: "Speakers"
    schedule: "Schedule"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now!"
    link: "https://www.causeweb.org/cause/ecots/ecots18"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "Hugo"
      logo: "/img/cause_logo.png"
      url: "https://www.causeweb.org/cause/"

  # List of Partners
  Partners:
    - name: "Hugo"
      logo: "/img/hugo.jpg"
      url: "https://gohugo.io"
    - name: "BrazilJS"
      logo: "/img/partner.png"
      url: "http://braziljs.org"

  # The entire schedule
  Schedule:

    - name: "Deborah Rumsey (Keynote Speaker)"
      photo: 
      bio: "Dr.Rumsey specializes in statistics education and has written a number of papers and given many talks and workshops on the subject. Her special interests include introductory statistics curriculum and development, teacher training and support, and designing learning spaces."
      company: "The Ohio State University"
      link:
        href: "https://stat.osu.edu/people/rumsey-johnson.1"
        text:  Deborah's Page
      presentation:
        title: "Keynote Address"
        description:
        time: 

    - name: "Homer White"
      photo: "/img/homer_white.jpg"
      bio: "Homer teaches Computer Science and Statistics, with a focus on computing for data analysis."
      company: "Georgetown College"
      link:
        href: "https://homerhanumat.com"
        text: "Homer's Blog"
      presentation:
        title: "Data Science in a Liberal Arts College"
        description: "Is Data Science a 'science'?  How might the answer to that question affect curricular decisions regarding Data Science at a liberal arts college?  In this talk I'll report on how we approach these issues at Georgetown College, and describe a revised Computer Science minor that aims to bring elements of Data Science to students from a potentially wide variety of disciplines."
        time: 

    - name: 
      photo: 
      bio: 
      company: 
      link:
        href: 
        text: 
      presentation:
        title: "More Speakers to be Announced Soon!"
        description:
        time: 
        

